---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: collector

resources:
  - ../base/

patches:
  - target:
      kind: OpenTelemetryCollector
      name: collector
    patch: |-
      - op: replace
        path: /metadata/name
        value: gitproviderreceiver
      - op: add
        path: /spec/envFrom
        value: 
          - secretRef:
              name: github-pat

configMapGenerator:
  - name: collector-config
    files:
      - colconfig.yaml
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

replacements:
  - source:
      kind: ConfigMap
      name: collector-config
      fieldPath: data.[colconfig.yaml]

    targets:
      - select:
          kind: OpenTelemetryCollector
        fieldPaths:
          - spec.config
        options:
          create: true
