---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: collector

patches:
  - target:
      kind: OpenTelemetryCollector
      name: collector
    patch: |-
      - op: replace
        path: /metadata/name
        value: gateway
      - op: add
        path: /spec/serviceAccount
        value: otel-collector

configMapGenerator:
  - name: gateway-collector-config
    files:
      - colconfig.yaml
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

replacements:
  - source:
      kind: ConfigMap
      name: gateway-collector-config
      fieldPath: data.[colconfig.yaml]

    targets:
      - select:
          kind: OpenTelemetryCollector
        fieldPaths:
          - spec.config
        options:
          create: true

resources:
  - ../../cluster-infra/namespace
  - ../base/
  - rbac.yaml
  - sa.yaml
  # - netpol.yaml
