---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: collector

patches:
  - target:
      kind: OpenTelemetryCollector
      name: collector
    patch: |-
      - op: replace
        path: /metadata/name
        value: gateway
      - op: add
        path: /spec/serviceAccount
        value: otel-collector

resources:
  - ../../cluster-infra/namespace
  - ../base/
  - rbac.yaml
  - sa.yaml
  # - netpol.yaml
