include("../../cluster-infra/otel-operator/Tiltfile")

k8s_yaml(kustomize("."))

k8s_resource(
  objects=[
    "gateway:opentelemetrycollector"
  ],
  new_name="gateway-collector",
  port_forwards=[
    port_forward(4317, 4317, name='otlp-grpc'),
    port_forward(4318, 4318, name'otlp-http')
  ],
  labels=[
    "gateway-collector"
  ],
  resource_deps=[
    "opentelemetry-operator-controller-manager"
  ]
)
