apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: loki
  name: loki
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.1.1
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/loki/config.yaml"
          ports:
            - containerPort: 3100
              name: loki
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: config
