{
 "title": "DORA VCS Metrics - Azure DevOps",
 "description": "VCS metrics for Azure DevOps repositories. Note: PR approval time metrics are not yet implemented in the ADO receiver. Includes metrics that align with Trunk Based Development and Small Batch Delivery.",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team",
    "label": "team",
    "query": {
     "query": "label_values(vcs_repository_count, team_name)"
    }
   },
   {
    "name": "repo",
    "label": "repo",
    "query": {
     "query": "label_values(vcs_ref_time{team_name=~\"$team\"}, vcs_repository_name)"
    }
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Branch Time Buckets",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "vcs_ref_time{vcs_repository_name=~\"$repo\", team_name=~\"$team\"} / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pull Request Open Time Buckets",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "vcs_change_duration{vcs_repository_name=~\"$repo\", team_name=~\"$team\", vcs_change_state=\"open\"} / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Trunk Based Development", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Average Branch Age (Days)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(team_name) (vcs_ref_time{vcs_repository_name=~\"$repo\", team_name=~\"$team\"}) / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Branch Age (Days)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_ref_time{vcs_repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{vcs_repository_name}}/{{ref_name}}"
    }
   ]
  },
  {
   "title": "Average Open Branches",
   "type": "stat",
   "description": "Average Open Branches",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(team_name) (vcs_ref_count{vcs_repository_name=~\"$repo\", team_name=~\"$team\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Branches",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Branches" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(vcs_repository_name) (vcs_ref_count{team_name=~\"$team\", vcs_repository_name=~\"$repo\"} > 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Open Pull Request Duration (Days)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(team_name) (vcs_change_duration{team_name=~\"$team\", vcs_repository_name=~\"$repo\", vcs_change_state=\"open\"}) / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "vcs_change_duration{vcs_repository_name=~\"$repo\", team_name=~\"$team\",vcs_change_state=\"open\"} / 86400",
     "legendFormat": "{{vcs_repository_name}}/{{ref_name}}"
    }
   ]
  },
  { "title": "Detailed VCS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Repo Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vcs_repository_count{team_name=~\"$team\"}",
     "legendFormat": "{{team_name}}"
    }
   ]
  },
  {
   "title": "Average Branch Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(avg by(team_name) (vcs_ref_count{vcs_repository_name=~\"$repo\", team_name=~\"$team\"})) > 1",
     "legendFormat": "{{team_name}}"
    }
   ]
  },
  {
   "title": "Average  Open Pull Request Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(avg by(team_name) (vcs_change_count{ vcs_repository_name=~\"$repo\", team_name=~\"$team\", vcs_change_state=\"open\"})) > 1",
     "legendFormat": "{{team_name}}"
    }
   ]
  },
  {
   "title": "Average Branch Age Per Repo In Days",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(vcs_repository_name) (vcs_ref_time{vcs_repository_name=~\"$repo\", team_name=~\"$team\"}) / 86400",
     "legendFormat": "{{vcs_repository_name}}"
    }
   ]
  },
  {
   "title": "Contributor Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "vcs_contributor_count{vcs_repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{vcs_repository_name}}"
    }
   ]
  },
  {
   "title": "Branch Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "vcs_ref_count{vcs_repository_name=~\"$repo\", team_name=~\"$team\"} - 1",
     "legendFormat": "{{vcs_repository_name}}"
    }
   ]
  },
  {
   "title": "Branch Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_ref_time{vcs_repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{vcs_repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Open Pull Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "vcs_change_count{vcs_change_state=\"open\", vcs_repository_name=~\"$repo\"}",
     "legendFormat": "{{vcs_repository_name}}"
    }
   ]
  },
  {
   "title": "Open Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_change_duration{vcs_repository_name=~\"$repo\", team_name=~\"$team\", vcs_change_state=\"open\"}",
     "legendFormat": "{{vcs_repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Merged Pull Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "vcs_change_count{vcs_change_state=\"merged\", vcs_repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{vcs_repository_name}}"
    }
   ]
  },
  {
   "title": "Merged Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_change_time_to_merge{vcs_repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{vcs_repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Code Coverage by Repository",
   "type": "timeseries",
   "description": "Code coverage percentage by repository and branch",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vcs_code_coverage{team_name=~\"$team\", vcs_repository_name=~\"$repo\"}",
     "legendFormat": "{{vcs_repository_name}} - {{vcs_ref_head_name}}"
    }
   ]
  },
  {
   "title": "Average Code Coverage",
   "type": "gauge",
   "description": "Average code coverage across all repositories",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(vcs_code_coverage{team_name=~\"$team\", vcs_repository_name=~\"$repo\"})"
    }
   ]
  }
 ]
}