{
 "title": "DORA Version Control System Capability Metrics",
 "description": "Includes metrics that align with Trunk Based Development and Small Batch Delivery.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "organization",
    "label": "organization",
    "query": {
     "query": "label_values(organization_name)"
    }
   },
   {
    "name": "team",
    "label": "team",
    "query": {
     "query": "label_values({organization_name=\"$organization\"},team_name)"
    }
   },
   {
    "name": "repo",
    "label": "repo",
    "query": {
     "query": "label_values({team_name=~\"$team\"},vcs_repository_name)"
    }
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Branch Time Buckets",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "vcs_ref_time_seconds{organization_name=~\"$organization\", vcs_repository_name=~\"$repo\", team_name=\"$team\"} / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pull Request Open Time Buckets",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "vcs_change_duration_seconds{organization_name=~\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\", vcs_change_state=\"open\"} / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Trunk Based Development", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Average Branch Age (Days)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(team_name) (vcs_ref_time_seconds{organization_name=~\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\"}) / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Branch Age (Days)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_ref_time_seconds{organization_name=\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{{{organization_name}}/{{repository_name}}/{{ref_name}}}}"
    }
   ]
  },
  {
   "title": "Average Open Branches",
   "type": "stat",
   "description": "Average Open Branches",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(team_name) (vcs_ref_count{organization_name=~\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Branches",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Branches" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(repository_name) (vcs_ref_count{organization_name=~\"$organization\", team_name=~\"$team\", vcs_repository_name=~\"$repo\"} > 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Open Pull Request Duration (Days)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(team_name) (vcs_change_duration_seconds{organization_name=~\"$organization\", team_name=~\"$team\", vcs_repository_name=~\"$repo\", vcs_change_state=\"open\"}) / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "vcs_change_duration_seconds{organization_name=~\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\",vcs_change_state=\"open\"} / 86400",
     "legendFormat": "{{repository_name}}/{{ref_name}}"
    }
   ]
  },
  { "title": "Build In Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Critical Vulnerabilities (CVEs)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(avg by(cve_severity) (vcs_cve_count{organization_name=~\"$organization\", team_name=~\"$team\", vcs_repository_name=~\"$repo\", cve_severity=\"critical\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vulnerabilities by Repo",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 17, "x": 7, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(repository_name) (vcs_cve_count{organization_name=~\"$organization\", team_name=~\"$team\", vcs_repository_name=~\"$repo\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "High Vulnerabilities (CVEs)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(cve_severity) (vcs_cve_count{organization_name=~\"$organization\", team_name=~\"$team\", vcs_repository_name=~\"$repo\", cve_severity=\"high\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Detailed VCS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Repo Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vcs_repository_count{organization_name=\"$organization\", team_name=~\"$team\"}",
     "legendFormat": "{{organization_name}}"
    }
   ]
  },
  {
   "title": "Average Branch Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(avg by(team_name) (vcs_ref_count{organization_name=~\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\"})) > 1",
     "legendFormat": "{{organization_name}}"
    }
   ]
  },
  {
   "title": "Average  Open Pull Request Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(avg by(team_name) (vcs_change_count{organization_name=~\"$organization\",  vcs_repository_name=~\"$repo\", team_name=~\"$team\", vcs_change_state=\"open\"})) > 1",
     "legendFormat": "{{organization_name}}"
    }
   ]
  },
  {
   "title": "Average Branch Age Per Repo In Days",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(repository_name) (vcs_ref_time_seconds{organization_name=\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\"}) / 86400",
     "legendFormat": "{{repository_name}}"
    }
   ]
  },
  {
   "title": "Contributor Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "vcs_contributor_count{organization_name=\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}"
    }
   ]
  },
  {
   "title": "Branch Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "vcs_ref_count{organization_name=\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\"} - 1",
     "legendFormat": "{{organization_name}}/{{repository_name}}"
    }
   ]
  },
  {
   "title": "Branch Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_ref_time_seconds{organization_name=\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Open Pull Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "vcs_change_count{vcs_change_state=\"open\", organization_name=\"$organization\", vcs_repository_name=~\"$repo\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}"
    }
   ]
  },
  {
   "title": "Open Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_change_duration_seconds{organization_name=\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\", vcs_change_state=\"open\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Approved Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_change_time_to_approval{organization_name=~\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Merged Pull Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "vcs_change_count{vcs_change_state=\"merged\", organization_name=~\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}"
    }
   ]
  },
  {
   "title": "Merged Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_change_time_to_merge_seconds{organization_name=~\"$organization\", vcs_repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  }
 ]
}