---
extensions:
  health_check:

  pprof:
    endpoint: 0.0.0.0:1777

  zpages:
    endpoint: 0.0.0.0:55679

  # bearertokenauth/o11y:
  #   token: ${env:GH_PAT}

  # bearertokenauth/backstage:
  #   token: ${env:GH_PAT}

  # bearertokenauth/autogov:
  #   token: ${env:GH_PAT}

  # bearertokenauth/operations:
  #   token: ${env:GH_PAT}

receivers:
  gitprovider/o11y:
    initial_delay: 10s
    collection_interval: 300s
    scrapers:
      github:
        github_org: liatrio
        search_query: org:liatrio topic:o11y archived:false
        # auth:
        #   authenticator: bearertokenauth/o11y
        metrics:
          git.repository.contributor.count:
            enabled: true

  gitprovider/backstage:
    initial_delay: 10s
    collection_interval: 300s
    scrapers:
      github:
        github_org: liatrio
        search_query: org:liatrio topic:backstage archived:false
        # auth:
        #   authenticator: bearertokenauth/backstage
        metrics:
          git.repository.contributor.count:
            enabled: true

  gitprovider/autogov:
    initial_delay: 10s
    collection_interval: 300s
    scrapers:
      github:
        github_org: liatrio
        search_query: org:liatrio topic:automated-governance archived:false
        # auth:
        #   authenticator: bearertokenauth/autogov
        metrics:
          git.repository.contributor.count:
            enabled: true

  gitprovider/operations:
    initial_delay: 10s
    collection_interval: 300s
    scrapers:
      github:
        github_org: liatrio
        search_query: org:liatrio topic:operations archived:false
        # auth:
        #   authenticator: bearertokenauth/operations
        metrics:
          git.repository.contributor.count:
            enabled: true

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15

  batch:
    send_batch_size: 100
    timeout: 10s

  resource/o11y:
    attributes:
      - key: team.name
        value: tag-o11y
        action: upsert

  resource/backstage:
    attributes:
      - key: team.name
        value: tag-devex
        action: upsert

  resource/autogov:
    attributes:
      - key: team.name
        value: tag-autogov
        action: upsert

  resource/operations:
    attributes:
      - key: team.name
        value: operations
        action: upsert

  filter/ottl:
    error_mode: ignore
    metrics:
      metric:
        - name == "rpc.server.duration"

  transform:
    metric_statements:
      - context: metric
        statements:
          - set(description, "") where name == "queueSize"
          - set(description, "") where name == "http.client.duration"

exporters:
  debug:
    verbosity: basic
    sampling_initial: 2
    sampling_thereafter: 500

  otlp:
    endpoint: http://tempo.collector.svc.cluster.local:4317
    tls:
      insecure: true
  
  prometheusremotewrite:
    endpoint: http://prometheus.collector.svc.cluster.local:9090/api/v1/write
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: true
    tls:
      insecure: true

  loki:
    endpoint: http://loki.collector.svc.cluster.local:3100/loki/api/v1/push

service:
  extensions: [health_check, pprof, zpages ]
    # bearertokenauth/o11y, 
    # bearertokenauth/backstage, 
    # bearertokenauth/autogov, 
    # bearertokenauth/operations
  pipelines:
    metrics:
      receivers: [gitprovider/o11y]
      processors: [memory_limiter, batch, resource/o11y]
      exporters: [debug, prometheusremotewrite]

    metrics/backstage:
      receivers: [gitprovider/backstage]
      processors: [memory_limiter, batch, resource/backstage]
      exporters: [debug, prometheusremotewrite]

    metrics/autogov:
      receivers: [gitprovider/autogov]
      processors: [memory_limiter, batch, resource/autogov]
      exporters: [debug, prometheusremotewrite]

    metrics/operations:
      receivers: [gitprovider/operations]
      processors: [memory_limiter, batch, resource/operations]
      exporters: [debug, prometheusremotewrite]
    
    # logs:
    #   receivers: [otlp]
    #   processors: [memory_limiter, batch]
    #   exporters: [debug, loki]

    # traces:
    #   receivers: [otlp]
    #   processors: [memory_limiter, batch]
    #   exporters: [debug, otlphttp/otel, spanmetrics]

