{
 "title": "Delivery-Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "organization", "label": "organization", "query": { "query": "label_values($organization)" } },
   { "name": "repository", "query": { "query": "label_values(repository_name)" } },
   { "name": "team", "label": "team", "query": { "query": "label_values(team_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Open Branches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(avg by(team_name) (git_repository_branch_count{organization_name=~\"liatrio\", repository_name=~\"$repository\", team_name=~\"$team\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Branches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "git_repository_branch_count{organization_name=~\"liatrio\", repository_name=~\"$repository\", team_name=~\"$team\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Pull Request Open Time (days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(team_name) (git_repository_pull_request_time_open{organization_name=~\"liatrio\", repository_name=~\"$repository\", team_name=~\"$team\"} / 86400)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Pull Request Open Time (days)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "git_repository_pull_request_time_open{organization_name=~\"liatrio\", repository_name=~\"$repository\", team_name=~\"$team\"} / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contributor Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "git_repository_branch_time{organization_name=~\"liatrio\", repository_name=~\"$repository\", team_name=~\"$team\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contributor Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "git_repository_branch_count{organization_name=~\"liatrio\", repository_name=~\"$repository\", team_name=~\"$team\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repository Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "git_repository_count{organization_name=~\"liatrio\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Age Per Repo in Days",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "git_repository_branch_time{organization_name=~\"liatrio\", repository_name=~\"$repository\"} / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Pull Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "git_repository_pull_request_count{organization_name=~\"liatrio\", repository_name=~\"$repository\", team_name=~\"$team\", pull_request_state=~\"open\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "git_repository_pull_request_time_open{organization_name=~\"liatrio\", repository_name=~\"$repository\", team_name=~\"$team\"} / 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pull Request Approval Time (days)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "git_repository_pull_request_time_to_approval{organization_name=~\"liatrio\", repository_name=~\"$repository\", team_name=~\"$team\"} / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merged Pull Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "git_repository_pull_request_count{organization_name=~\"liatrio\", repository_name=~\"$repository\", team_name=~\"$team\", pull_request_state=~\"merged\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merged Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "git_repository_pull_request_time_to_merge{organization_name=~\"liatrio\", repository_name=~\"$repository\", team_name=~\"$team\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}