---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki

resources:
  - ../../cluster-infra/namespace
  - deployment.yaml
  - service.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: loki

configMapGenerator:
  - name: config
    files:
      - config.yaml
