---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - ../../../cluster-infra/namespace
  - deployment.yaml
  - pvc.yaml
  - service.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: grafana

configMapGenerator:
  - name: grafana-ini
    files:
      - grafana.ini
  - name: datasources
    files:
      - datasources.yaml
  - name: providers
    files:
      - dashboards/providers.yaml


  # Demo Dashboards
  - name: dashboard-demo
    files:
      - dashboards/demo/demo.json
  - name: dashboard-opentelemetry-collector-data-flow
    files:
      - dashboards/demo/opentelemetry-collector-data-flow.json
  - name: dashboard-opentelemetry-collector
    files:
      - dashboards/demo/opentelemetry-collector.json
  - name: dashboard-spanmetrics
    files:
      - dashboards/demo/spanmetrics.json

  # GitProviderReceiver dashboards
  - name: dashboard-gpr-delivery-metrics
    files:
      - dashboards/gpr/delivery-metrics.json
  - name: dashboard-gpr-dora-metrics
    files:
      - dashboards/gpr/dora-metrics.json
  - name: dashboard-gpr-engineering-effectiveness-metrics
    files:
      - dashboards/gpr/engineering-effectiveness-metrics.json
  - name: dashboard-gpr-vcs-trunk-based-development
    files:
      - dashboards/gpr/vcs-trunk-based-development.json
