apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  ports:
    - port: 4317
      protocol: TCP
      targetPort: grpc
      name: grpc
    - port: 4318
      protocol: TCP
      targetPort: http
      name: http
    - port: 3200
      protocol: TCP
      targetPort: tempo
      name: tempo
  selector:
    app.kubernetes.io/name: tempo
  sessionAffinity: None
  type: LoadBalancer
