{
 "title": "SonarQube Analysis Dashboard",
 "description": "The Jersey Mikes SonarQube Analysis Dashboard provides detailed code quality metrics to help monitor and improve software quality across all projects.",
 "tags": [
  "jersey-mikes",
  "sonarqube",
  "code-quality"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": { "query": "label_values(sonar_lines,id)" } }
  ]
 },
 "panels": [
  { "title": "Quality gates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quality Gate Status",
   "type": "stat",
   "description": "The state of the quality gate associated with your project. Possible values are ERROR and OK",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{alert_status=\"OK\",id=~\"$project\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Line of Code",
   "type": "stat",
   "description": "- Lines (lines): The number of physical lines \n- Lines of code (ncloc): The number of physical lines that contain at least one character\n- Comment lines (comment_lines): The number of lines containing comment",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_comment_lines{id=~\"$project\"}",
     "legendFormat": "Comment Lines ({{id}})"
    },
    {
     "expr": "sonar_lines{id=~\"$project\"}",
     "legendFormat": "Lines ({{id}})"
    },
    {
     "expr": "sonar_lines_to_cover{id=~\"$project\"}",
     "legendFormat": "Lines To Cover ({{id}})"
    }
   ]
  },
  {
   "title": "The comment lines density",
   "type": "gauge",
   "description": "The comment lines density = comment lines / (lines of code + comment lines) * 100",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_comment_lines_density{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "The number of classes ",
   "type": "timeseries",
   "description": "The number of classes (including nested classes, interfaces, enums, and annotations).",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sonar_classes{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "The number of statements",
   "type": "stat",
   "description": "The number of statements.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_statements{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "The number of functions",
   "type": "stat",
   "description": "The number of functions. Depending on the language, a function is defined as either a function, a method, or a paragraph.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_functions{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "The number of files",
   "type": "stat",
   "description": "The number of files.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_files{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total of Issues",
   "type": "stat",
   "description": "The total count of issues in all states.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_violations{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Violations",
   "type": "piechart",
   "description": "The total count of issues of the specified severity, where xxx is one of: blocker, critical, major, minor, info.",
   "gridPos": { "h": 7, "w": 10, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_blocker_violations{id=~\"$project\"}",
     "legendFormat": "Blocker ({{id}})"
    },
    {
     "expr": "sonar_critical_violations{id=~\"$project\"}",
     "legendFormat": "Critical ({{id}})"
    },
    {
     "expr": "sonar_info_violations{id=~\"$project\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "sonar_major_violations{id=~\"$project\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "sonar_minor_violations{id=~\"$project\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "piechart",
   "description": "The total count of issues in the state.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_open_issues{id=~\"$project\"} ",
     "legendFormat": "Open ({{id}})"
    },
    {
     "expr": "sonar_reopened_issues{id=~\"$project\"} ",
     "legendFormat": "Reopened ({{id}})"
    },
    {
     "expr": "sonar_confirmed_issues{id=~\"$project\"} ",
     "legendFormat": "Confirmed ({{id}})"
    },
    {
     "expr": "sonar_false_positive_issues{id=~\"$project\"} ",
     "legendFormat": "False Positive ({{id}})"
    },
    {
     "expr": "sonar_wont_fix_issues{domain=\"Issues\",project_key=\"$project_key\"} ",
     "legendFormat": "Won't Fix ({{id}})"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "The number of vulnerability issues.",
   "type": "stat",
   "description": "The number of vulnerability issues.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_vulnerabilities{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "The effort to fix all vulnerability issues",
   "type": "stat",
   "description": "The measure is stored in minutes in the DB. An 8-hour day is assumed when values are shown in days.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_security_remediation_effort{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "The number of Security Hotspots",
   "type": "stat",
   "description": "The number of Security Hotspots",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_security_hotspots{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Security Rating",
   "type": "stat",
   "description": "Security Rating (security_rating)\n- A = 0 Vulnerabilities\n- B = at least 1 Minor Vulnerability\n- C = at least 1 Major Vulnerability\n- D = at least 1 Critical Vulnerability\n- E = at least 1 Blocker Vulnerability",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_security_rating{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Security review rating",
   "type": "stat",
   "description": "The security review rating is a letter grade based on the percentage of Reviewed Security Hotspots.\n- A = >= 80%\n- B = >= 70% and <80%\n- C = >= 50% and <70%\n- D = >= 30% and <50%\n- E = < 30%",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_security_review_rating{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Duplications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Duplications",
   "type": "stat",
   "description": "- Duplicated blocks (duplicated_blocks): The number of duplicated blocks of lines.\n- Duplicated lines (duplicated_lines): The number of lines involved in duplications.\n- Duplicated files (duplicated_files): The number of files involved in duplications.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_duplicated_lines{id=~\"$project\"}",
     "legendFormat": "Duplicated Lines ({{id}})"
    },
    {
     "expr": "sonar_duplicated_files{id=~\"$project\"} ",
     "legendFormat": "Duplicated Files ({{id}})"
    },
    {
     "expr": "sonar_duplicated_blocks{id=~\"$project\"}",
     "legendFormat": "Duplicated Blocks ({{id}})"
    }
   ]
  },
  {
   "title": "Duplicated Lines (%)",
   "type": "gauge",
   "description": "Duplicated lines (%) (duplicated_lines_density): duplicated_lines / (lines of code) * 100",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Coverage",
   "type": "gauge",
   "description": "Coverage = (CT + CF + LC)/(2*B + EL)\nwhere:\n- CT = conditions that have been evaluated to 'true' at least once\n- CF = conditions that have been evaluated to 'false' at least once\n- LC = covered lines = linestocover - uncovered_lines\n- B = total number of conditions\n- EL = total number of executable lines (lines_to_cover)\n",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_coverage{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "The number of lines that covered by unit test",
   "type": "stat",
   "description": "The number of lines of code that could be covered by unit tests (for example, blank lines or full comments lines are not considered as lines to cover).",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_lines_to_cover{id=~\"$project\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The number of unit tests.",
   "type": "stat",
   "description": "The number of unit tests.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_tests{id=~\"$project_key\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "The frequencies of rule",
   "type": "bargauge",
   "description": "The number append of rule in scan result ",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_stat_rule{id=~\"$project\"}",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  { "title": "Reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "The total number of bug issues",
   "type": "stat",
   "description": "The total number of bug issues.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_bugs{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Reliability Rating",
   "type": "stat",
   "description": "- A = 0 Bugs\n- B = at least 1 Minor Bug\n- C = at least 1 Major Bug\n- D = at least 1 Critical Bug\n- E = at least 1 Blocker Bug",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_reliability_rating{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "The effort to fix all bug issues",
   "type": "stat",
   "description": "The measure is stored in minutes in the DB. An 8-hour day is assumed when values are shown in days.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_reliability_remediation_effort{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Maintainability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "The total count of code smell issues",
   "type": "stat",
   "description": "The total count of code smell issues.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_code_smells{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Maintainability Rating",
   "type": "gauge",
   "description": "Formerly the SQALE rating.) The rating given to your project related to the value of your technical debt ratio. The default maintainability rating grid is:\n\n- A=0-0.05, B=0.06-0.1, C=0.11-0.20, D=0.21-0.5, E=0.51-1",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_sqale_rating{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "stat",
   "description": "A measure of effort to fix all code smells. The measure is stored in minutes in the database. An 8-hour day is assumed when values are shown in days.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_sqale_index{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Complexity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Complexity / File",
   "type": "stat",
   "description": "Complexity / File",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_file_complexity{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Cognitive Complexity",
   "type": "stat",
   "description": "How hard it is to understand the code's control flow",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_cognitive_complexity{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Cyclomatic Complexity",
   "type": "stat",
   "description": "Complexity refers to cyclomatic complexity, a quantitative metric used to calculate the number of paths through the code.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_complexity{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Project analyses events",
   "type": "table",
   "description": "Project analyses events",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sonar_project_analyses_and_events_info{id=~\"$project\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}