---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elastic-system

resources:
  - helm-chart.yaml
  - ingress.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: eck-stack
