apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - name: pv
              mountPath: /var/lib/grafana
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-ini
              mountPath: /etc/grafana/provisioning
            - name: providers
              mountPath: /etc/grafana/provisioning/dashboards

            # Demo Dashboards
            - name: opentofu-controller-demo
              mountPath: /etc/grafana/provisioning/dashboards/demo/opentofu-controller-demo.json

      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: pvc
        - name: grafana-ini
          configMap:
            name: grafana-ini
        - name: datasources
          configMap:
            name: datasources
        - name: providers
          configMap:
            name: providers

        # Demo Dashboards
        - name: opentofu-controller-demo
          configMap:
            name: opentofu-controller-demo
