{
 "title": "VCS Trunk Based Development",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Trunk Based Development", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Ref Age (Days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(team_name) (vcs_repository_ref_time_seconds) / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Ref Age (Days)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_repository_ref_time_seconds",
     "legendFormat": "{{repository_name}}/{{ref_name}}"
    }
   ]
  },
  {
   "title": "Open Refs",
   "type": "stat",
   "description": "Open Branches",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(team_name) (vcs_repository_ref_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Refs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg by(repository_name) (vcs_repository_ref_count > 1)",
     "legendFormat": "{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Open Change Duration (Days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(team_name) (vcs_repository_change_time_open_seconds) / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Change Age",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_repository_change_time_open_seconds",
     "legendFormat": "{{repository_name}}/{{ref_name}}"
    }
   ]
  }
 ]
}