---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - ../../../cluster-infra/namespace
  - deployment.yaml
  - pvc.yaml
  - service.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: grafana

configMapGenerator:
  - name: grafana-ini
    files:
      - grafana.ini
  - name: datasources
    files:
      - datasources.yaml
  - name: providers
    files:
      - dashboards/providers.yaml

  # Demo Dashboards
  - name: opentofu-controller-demo
    files:
      - dashboards/demo/opentofu-controller-demo.json
