{
 "title": "OpenTofu controller dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "module_source",
    "label": "module_source",
    "query": {}
   },
   {
    "name": "team",
    "label": "team",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Data by module source and team", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Adoption by Version",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.applied=\"true\" && .service.name=\"OpenTofu Controller\"} >> {.team=\"$team\"} >> {.module_ref!=\"nil\" && .module_source=\"$module_source\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Adoption by Version",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.applied=\"true\" && .service.name=\"OpenTofu Controller\"} >> {.team=\"$team\"} >> {.module_ref!=\"nil\" && .module_source=\"$module_source\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Adoption by Version including ones not applied",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.service.name=\"OpenTofu Controller\"} >> {.team=\"$team\"} >> {.module_ref!=\"nil\" && .module_source=\"$module_source\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Adoption by Version including ones not applied",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.service.name=\"OpenTofu Controller\"} >> {.team=\"$team\"} >> {.module_ref!=\"nil\" && .module_source=\"$module_source\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Errors by Version",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.applied=\"true\" && .service.name=\"OpenTofu Controller\"} >> {.module_with_error_source=\"$module_source\" && .module_with_error_ref!=\"nil\" && .team=\"$team\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Errors by Version",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.applied=\"true\" && .service.name=\"OpenTofu Controller\"} >> {.module_with_error_source=\"$module_source\" && .module_with_error_ref!=\"nil\" && .team=\"$team\"}",
     "tableType": "spans"
    }
   ]
  },
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Adoption",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.service.name=\"OpenTofu Controller\" && .applied=\"true\"} >> {.module_ref!=\"nil\" && .module_source!=\"nil\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Adoption by Module",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.service.name=\"OpenTofu Controller\" && .applied=\"true\"} >> {.module_source!=\"nil\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.service.name=\"OpenTofu Controller\" && .applied=\"true\"} >> {.module_with_error_source!=\"nil\" && .module_with_error_ref!=\"nil\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Errors by Module",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.service.name=\"OpenTofu Controller\" && .applied=\"true\"} >> {.module_with_error_source!=\"nil\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Trace Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "filters": [
      {
       "id": "9f0df7d0",
       "operator": "=",
       "scope": "span",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "OpenTofu Controller" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}