apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          imagePullPolicy: IfNotPresent
          args:
            - "--web.enable-remote-write-receiver"
            - "--config.file=/etc/prometheus/config.yaml"
            - "--storage.tsdb.path=/prometheus/"

          ports:
            - containerPort: 9090
              name: prometheus
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/config.yaml
              subPath: config.yaml
            - name: storage
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: config
        - name: storage
          emptyDir: {}
