if k8s_context() != "${K8S_PLATFORM}-otel-basic":
  fail("Expected context to be ${K8S_PLATFORM}-otel-basic")

k8s_yaml(kustomize("."), allow_duplicates=True)

k8s_resource(
  objects=[
    "otel-webhook-collector:opentelemetrycollector"
  ],
  new_name="otel-webhook-collector",
  port_forwards=[
    port_forward(9999, 9999, name='webhook-events')
  ],
  labels=[
    "otel-webhook-collector"
  ],
  resource_deps=[
    "opentelemetry-operator-controller-manager"
  ]
)
