---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaeger

resources:
  - ../../cluster-infra/namespace/
  - jaeger.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: jaeger
