apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: prometheus
  selector:
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: LoadBalancer
