{
 "title": "Engineering Effectiveness Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "organization",
    "label": "organization",
    "query": {
     "query": "label_values(organization_name)"
    }
   },
   {
    "name": "team",
    "label": "team",
    "query": {
     "query": "label_values({organization_name=\"$organization\"},team_name)"
    }
   },
   {
    "name": "repo",
    "label": "repo",
    "query": {
     "query": "label_values({team_name=~\"$team\"},repository_name)"
    }
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Trunk Based Development", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Branch Age (Days)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(team_name) (git_repository_branch_time_seconds{organization_name=~\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"}) / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Branch Age (Days)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "git_repository_branch_time_seconds{organization_name=\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{{{organization_name}}/{{repository_name}}/{{branch_name}}}}"
    }
   ]
  },
  {
   "title": "Average Open Branches",
   "type": "stat",
   "description": "Average Open Branches",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(team_name) (git_repository_branch_count{organization_name=~\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Branches",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Branches" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(repository_name) (git_repository_branch_count{organization_name=~\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"} > 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Open Pull Request Duration (Days)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(team_name) (git_repository_pull_request_time_open_seconds{organization_name=\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"}) / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "git_repository_pull_request_time_open_seconds{organization_name=~\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"} / 86400",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  { "title": "Build In Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Critical Vulnerabilities (CVEs)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(cve_severity) (git_repository_cve_count{organization_name=~\"$organization\", team_name=~\"$team\", repository_name=~\"$repo\", cve_severity=\"critical\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vulnerabilities by Repo",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 17, "x": 7, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(repository_name) (git_repository_cve_count{organization_name=~\"$organization\", team_name=~\"$team\", repository_name=~\"$repo\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "High Vulnerabilities (CVEs)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(cve_severity) (git_repository_cve_count{organization_name=~\"$organization\", team_name=~\"$team\", repository_name=~\"$repo\", cve_severity=\"high\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Detailed Git Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Repo Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "git_repository_count{organization_name=\"$organization\", team_name=~\"$team\"}",
     "legendFormat": "{{organization_name}}"
    }
   ]
  },
  {
   "title": "Average Branch Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(avg by(team_name) (git_repository_branch_count{organization_name=~\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"} > 1))",
     "legendFormat": "{{organization_name}}"
    }
   ]
  },
  {
   "title": "Average Branch Age Per Repo In Days",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(repository_name) (git_repository_branch_time_seconds{organization_name=\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"}) / 86400",
     "legendFormat": "{{repository_name}}"
    }
   ]
  },
  {
   "title": "Contributor Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "git_repository_contributor_count{organization_name=\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}"
    }
   ]
  },
  {
   "title": "Branch Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "git_repository_branch_count{organization_name=\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"} - 1",
     "legendFormat": "{{organization_name}}/{{repository_name}}"
    }
   ]
  },
  {
   "title": "Branch Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "git_repository_branch_time_seconds{organization_name=\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Open Pull Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "git_repository_pull_request_count{pull_request_state=\"open\", organization_name=\"$organization\", repository_name=~\"$repo\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}"
    }
   ]
  },
  {
   "title": "Open Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "git_repository_pull_request_time_open_seconds{organization_name=\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Approved Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "git_repository_pull_request_time_to_approval_seconds{organization_name=~\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Merged Pull Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "git_repository_pull_request_count{pull_request_state=\"merged\", organization_name=~\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}"
    }
   ]
  },
  {
   "title": "Merged Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "git_repository_pull_request_time_to_merge_seconds{organization_name=~\"$organization\", repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  }
 ]
}