---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - ../namespace
  - https://github.com/jaegertracing/jaeger-operator/releases/download/v1.57.0/jaeger-operator.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: jaeger-operator
