---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
# - ../namespace
- https://github.com/fluxcd/flux2/releases/latest/download/install.yaml
#   currently an issue with how large the last-applied annotation is, moved it out to the makefile with a kubectl create
# - https://github.com/flux-iac/tofu-controller/releases/download/v0.15.1/tf-controller.crds.yaml
- https://github.com/flux-iac/tofu-controller/releases/download/v0.15.1/tf-controller.rbac.yaml
- ./deployment.yml
- ./source_control.yml
- ./terraform1.yml
- ./terraform2.yml
- ./terraform3.yml


