apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: demo1
  labels:
    tracing.attributes/team: o11y
spec:
  path: ./main_with_error/
  interval: 5m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  sourceRef:
    kind: GitRepository
    name: demo-source
    namespace: flux-system
  runnerPodTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: tf-runner
        app.kubernetes.io/created-by: tf-controller
    spec:
      env:
        - name: ENABLE_SENSITIVE_TF_LOGS
          value: "1"
        

