{
 "title": "OpenTofu controller dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "module_ref",
    "label": "module_ref",
    "query": {}
   },
   {
    "name": "module_source",
    "label": "module_source",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Adoption by Version",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.applied=\"true\"} >> {.module_ref!=\"nil\" && .module_source=\"$module_source\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Adoption by Version",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.applied=\"true\"} >> {.module_ref!=\"nil\" && .module_source=\"$module_source\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Adoption by Version including ones not applied",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.service.name=\"OpenTofu Controller\"}>>{.module_ref!=\"nil\" && .module_source=\"$module_source\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Adoption by Version",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.service.name=\"OpenTofu Controller\"}>>{.module_ref!=\"nil\" && .module_source=\"$module_source\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Errors by Version",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.applied=\"true\"} >> {.module_with_error_source=\"$module_source\" && .module_with_error_ref!=\"nil\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Errors by Version",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.applied=\"true\"} >> {.module_with_error_source=\"$module_source\" && .module_with_error_ref!=\"nil\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Adoption by Version",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "filters": [
      { "id": "ed49c182", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.module_ref!=\"nil\" && .module_source!=\"nil\"}",
     "tableType": "spans"
    }
   ]
  }
 ]
}