if k8s_context() != "k3d-otel-basic":
  fail("Expected context to be k3d-otel-basic")

k8s_yaml(kustomize("."), allow_duplicates=True)

k8s_resource(
  workload="openobserve",
  port_forwards=5080,
  labels=[
    "openobserve"
  ]
)

# The bootstrap job needs to run after openobserve is up.
# Delete the old job first so it can be recreated on each Tilt up/reload.
local_resource(
  name="cleanup-dashboard-job",
  cmd="kubectl delete job openobserve-dashboard-bootstrap -n openobserve --ignore-not-found=true",
  labels=["openobserve"],
  resource_deps=[]
)

k8s_resource(
  workload="openobserve-dashboard-bootstrap",
  labels=["openobserve"],
  resource_deps=["openobserve", "cleanup-dashboard-job"]
)
