---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elastic-system

resources:
  - ../../cluster-infra/namespace
  - helm-chart.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: eck-operator