---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - localized.yaml
  #- https://download.elastic.co/downloads/eck/2.12.1/crds.yaml
  #- https://download.elastic.co/downloads/eck/2.12.1/operator.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: eck-operator
