apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: tempo
  name: tempo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          imagePullPolicy: IfNotPresent
          args: [-config.file=/conf/config.yaml]
          ports:
            - containerPort: 4317
              name: grpc
              protocol: TCP
            - containerPort: 4318
              name: http
              protocol: TCP
            - containerPort: 3200
              name: tempo
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/conf"

      volumes:
        - name: config
          configMap:
            name: config
