---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tempo

resources:
  - ../../cluster-infra/namespace/
  - deployment.yaml
  - service.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: tempo

configMapGenerator:
  - name: config
    files:
      - config.yaml
