apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  ports:
    - port: 3100
      protocol: TCP
      targetPort: loki
  selector:
    app.kubernetes.io/name: loki
  sessionAffinity: None
  type: LoadBalancer
