# These roles allow stock kubernetes cluster-roles to handle OpenTelemetry CRDs
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: opentelemetry-view
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: opentelemetry-view
rules:
  - apiGroups:
      - opentelemetry.io
    resources:
      - instrumentations
      - opampbridges
      - opentelemetrycollectors
      - opentelemetrycollectors/status
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: opentelemetry-edit
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: opentelemetry-edit
rules:
  - apiGroups:
      - opentelemetry.io
    resources:
      - instrumentations
      - opampbridges
      - opampbridges/finalizers
      - opentelemetrycollectors
      - opentelemetrycollectors/finalizers
      - opentelemetrycollectors/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
