include("../cert-manager/Tiltfile")

k8s_yaml(kustomize("."))

k8s_kind("validatingwebhookconfiguration")
k8s_kind("validatingwebhookconfiguration")

k8s_resource(
  workload="opentelemetry-operator-controller-manager",
  resource_deps=[
    "cert-manager",
    "cert-manager-cainjector",
    "cert-manager-webhook:deployment",
  ],
  labels=[
    "otel-operator"
  ]
)

k8s_resource(
  workload="opentelemetry-operator-mutating-webhook-configuration",
  pod_readiness="ignore",
  resource_deps=[
    "cert-manager-webhook:deployment",
  ],
  labels=[
    "otel-operator"
  ]
)

k8s_resource(
  workload="opentelemetry-operator-validating-webhook-configuration",
  pod_readiness="ignore",
  resource_deps=[
    "cert-manager-webhook:deployment",
  ],
  labels=[
    "otel-operator"
  ]
)