---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: collector

resources:
  - ../base/
  - sa.yaml
  - ngrok-route.yaml

patches:
  - target:
      kind: OpenTelemetryCollector
      name: collector
    patch: |-
      - op: replace
        path: /spec/image
        value: ghcr.io/krzko/otelcol-distributions/githubactions:0.99.1
      - op: replace
        path: /metadata/name
        value: otel-gha-collector
      - op: replace
        path: /spec/serviceAccount
        value: otel-gha-collector
      - op: replace
        path: /spec/ports
        value:
          - name: gha-port
            port: 8088
            protocol: TCP
            targetPort: 8088

configMapGenerator:
  - name: collector-config
    files:
      - colconfig.yaml
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

replacements:
  - source:
      kind: ConfigMap
      name: collector-config
      fieldPath: data.[colconfig.yaml]

    targets:
      - select:
          kind: OpenTelemetryCollector
        fieldPaths:
          - spec.config
        options:
          create: true
