---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: collector

resources:
  - ../base/
  - ingress.yaml

patches:
  - target:
      kind: OpenTelemetryCollector
      name: collector
    path: colconfig.yaml
  - target:
      kind: OpenTelemetryCollector
      name: collector
    patch: |-
      - op: replace
        path: /metadata/name
        value: gateway-eck
      - op: add
        path: /spec/serviceAccount
        value: otel-collector
      - op: add
        path: /spec/env
        value: 
          - name: AMP_TOKEN
            valueFrom:
              secretKeyRef:
                name: eck-stack-apm-server-apm-token
                key: secret-token

# Config map generator set the collector config as a multi-line string. OTEL operator v1beta1 expects an object rather than a string.
# configMapGenerator:
#   - name: collector-config
#     files:
#       - colconfig.yaml
#     options:
#       annotations:
#         config.kubernetes.io/local-config: "true"

# replacements:
#   - source:
#       kind: ConfigMap
#       name: collector-config
#       fieldPath: data.[colconfig.yaml]

#     targets:
#       - select:
#           kind: OpenTelemetryCollector
#         fieldPaths:
#           - spec.config
#         options:
#           create: true
