if k8s_context() != "k3d-otel-basic":
  fail("Expected context to be k3d-otel-basic")

k8s_yaml(kustomize("."), allow_duplicates=True)

k8s_resource(
  objects=[
    "otel-github-collector:opentelemetrycollector"
  ],
  new_name="otel-github-collector",
  labels=[
    "otel-github-collector"
  ],
  resource_deps=[
    "opentelemetry-operator-controller-manager"
  ]
)
