---
name: PR Linter

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
