---
name: Semantic Release

on:
  push:
    branches: [main]

jobs:
  go-semantic-release:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run go-semantic-release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-generator-opt: emojis=true
          allow-initial-development-versions: true
